modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/TheCBProject/Translocators"
license="The MIT License (MIT)"

[[mods]]
	modId="translocators"
	displayName="Translocators"
    version="${file.jarVersion}"

	updateJSONURL="https://version-check.covers1624.net/check/?mod=Translocators&mc=${mc_version}"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/translocators-1-8"
	authors="ChickenBones, covers1624"
	description='''
Translocates stuff!
    Credits: MouseCop - Textures
	'''
[[dependencies.translocators]]
	modId="neoforge"
    type="required"
	versionRange="[${forge_version},)"
	ordering="NONE"
	side="BOTH"
[[dependencies.translocators]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.translocators]]
    modId="codechickenlib"
    type="required"
    versionRange="${ccl_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.translocators]]
    modId="cb_multipart"
    type="required"
    versionRange="${cbmp_version_range}"
    ordering="AFTER"
    side="BOTH"
